before_install: 
  - TRAVIS_USERNAME=`echo $TRAVIS_REPO_SLUG | sed 's/\/.*//'`
  - git clone https://github.com/$TRAVIS_USERNAME/cmsdal.git $TRAVIS_USERNAME/cmsdal
  - cd $TRAVIS_USERNAME/cmsdal 
  - mvn clean install -Dmaven.test.skip=true
  - cd ../..
  - git clone https://github.com/$TRAVIS_USERNAME/oo-commons.git $TRAVIS_USERNAME/oo-commons
  - cd $TRAVIS_USERNAME/oo-commons
  - mvn clean install -Dmaven.test.skip=true
  - cd ../..
sudo: false
language: java
jdk: oraclejdk8
